#!/usr/bin/env node

/**
 * Asset Scanner & Registry Generator
 * 
 * Escaneia a pasta public/assets e gera:
 * 1. src/config/assets.ts - TypeScript registry
 * 2. assets-library.html - Página visual HTML
 * 3. docs/ASSETS-INVENTORY.md - Documentação markdown
 * 
 * Uso: node scan-assets.js
 */

const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(process.cwd(), 'public', 'assets');
const OUTPUT_DIR = process.cwd();

// Cores para log
const colors = {
  reset: '\x1b[0m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  magenta: '\x1b[35m',
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

// Scan directory recursively
function scanDirectory(dir, basePath = '') {
  const results = {
    images: [],
    videos: [],
    models: [],
    icons: [],
    patterns: [],
    frames: [],
  };

  if (!fs.existsSync(dir)) {
    log(`⚠️  Directory not found: ${dir}`, 'yellow');
    return results;
  }

  const items = fs.readdirSync(dir);

  items.forEach((item) => {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);
    const relativePath = path.join(basePath, item).replace(/\\/g, '/');

    if (stat.isDirectory()) {
      // Recursively scan subdirectories
      const subResults = scanDirectory(fullPath, relativePath);
      
      // Merge results
      Object.keys(subResults).forEach((key) => {
        results[key] = results[key].concat(subResults[key]);
      });
    } else {
      const ext = path.extname(item).toLowerCase();
      const name = path.basename(item, ext);
      const webPath = `/assets/${relativePath}`;

      // Categorize by extension
      if (['.jpg', '.jpeg', '.png', '.webp', '.avif'].includes(ext)) {
        // Check if it's a frame sequence
        if (/frame[_-]\d{4}/.test(name) || /\d{4}/.test(name)) {
          const folder = path.dirname(relativePath);
          if (!results.frames.find((f) => f.folder === folder)) {
            results.frames.push({
              name: folder.split('/').pop(),
              folder,
              path: `/assets/${folder}/`,
            });
          }
        } else {
          results.images.push({
            name,
            path: webPath,
            size: getFileSize(fullPath),
            category: getCategoryFromPath(relativePath),
          });
        }
      } else if (['.mp4', '.webm', '.mov'].includes(ext)) {
        results.videos.push({
          name,
          path: webPath,
          size: getFileSize(fullPath),
        });
      } else if (['.glb', '.gltf'].includes(ext)) {
        results.models.push({
          name,
          path: webPath,
          size: getFileSize(fullPath),
          format: ext.replace('.', '').toUpperCase(),
        });
      } else if (ext === '.svg') {
        if (relativePath.includes('icon')) {
          results.icons.push({
            name,
            path: webPath,
            category: getCategoryFromPath(relativePath),
          });
        } else {
          results.patterns.push({
            name,
            path: webPath,
          });
        }
      }
    }
  });

  return results;
}

function getCategoryFromPath(relativePath) {
  const parts = relativePath.split('/');
  return parts[0] || 'general';
}

function getFileSize(filePath) {
  const stats = fs.statSync(filePath);
  const sizeInBytes = stats.size;
  
  if (sizeInBytes < 1024) return `${sizeInBytes} B`;
  if (sizeInBytes < 1024 * 1024) return `${(sizeInBytes / 1024).toFixed(1)} KB`;
  return `${(sizeInBytes / (1024 * 1024)).toFixed(1)} MB`;
}

// Generate TypeScript registry
function generateTypeScriptRegistry(assets) {
  const grouped = {
    images: {},
    videos: [],
    models: [],
    icons: {},
    patterns: [],
    frames: [],
  };

  // Group images by category
  assets.images.forEach((img) => {
    if (!grouped.images[img.category]) {
      grouped.images[img.category] = [];
    }
    grouped.images[img.category].push(img);
  });

  // Group icons by category
  assets.icons.forEach((icon) => {
    if (!grouped.icons[icon.category]) {
      grouped.icons[icon.category] = [];
    }
    grouped.icons[icon.category].push(icon);
  });

  grouped.videos = assets.videos;
  grouped.models = assets.models;
  grouped.patterns = assets.patterns;
  grouped.frames = assets.frames;

  let ts = `// Auto-generated by scan-assets.js
// Do not edit manually - run 'node scan-assets.js' to regenerate

export const ASSETS = {
  images: {\n`;

  // Images
  Object.keys(grouped.images).forEach((category) => {
    ts += `    ${category}: {\n`;
    grouped.images[category].forEach((img) => {
      const key = img.name.replace(/[^a-zA-Z0-9]/g, '_');
      ts += `      ${key}: '${img.path}',\n`;
    });
    ts += `    },\n`;
  });

  ts += `  },\n\n  videos: {\n`;

  // Videos
  grouped.videos.forEach((video) => {
    const key = video.name.replace(/[^a-zA-Z0-9]/g, '_');
    ts += `    ${key}: '${video.path}',\n`;
  });

  ts += `  },\n\n  models: {\n`;

  // Models
  grouped.models.forEach((model) => {
    const key = model.name.replace(/[^a-zA-Z0-9]/g, '_');
    ts += `    ${key}: '${model.path}',\n`;
  });

  ts += `  },\n\n  icons: {\n`;

  // Icons
  Object.keys(grouped.icons).forEach((category) => {
    ts += `    ${category}: {\n`;
    grouped.icons[category].forEach((icon) => {
      const key = icon.name.replace(/[^a-zA-Z0-9]/g, '_');
      ts += `      ${key}: '${icon.path}',\n`;
    });
    ts += `    },\n`;
  });

  ts += `  },\n\n  patterns: {\n`;

  // Patterns
  grouped.patterns.forEach((pattern) => {
    const key = pattern.name.replace(/[^a-zA-Z0-9]/g, '_');
    ts += `    ${key}: '${pattern.path}',\n`;
  });

  ts += `  },\n\n  frames: {\n`;

  // Frame sequences
  grouped.frames.forEach((frame) => {
    const key = frame.name.replace(/[^a-zA-Z0-9]/g, '_');
    ts += `    ${key}: {\n`;
    ts += `      folder: '${frame.folder}',\n`;
    ts += `      path: '${frame.path}',\n`;
    ts += `    },\n`;
  });

  ts += `  },\n} as const;\n\n`;
  ts += `export type Assets = typeof ASSETS;\n`;

  return ts;
}

// Generate Markdown inventory
function generateMarkdownInventory(assets) {
  let md = `# Assets Inventory\n\n`;
  md += `**Auto-generated:** ${new Date().toISOString()}\n\n`;
  md += `## Summary\n\n`;
  md += `- **Images:** ${assets.images.length}\n`;
  md += `- **Videos:** ${assets.videos.length}\n`;
  md += `- **3D Models:** ${assets.models.length}\n`;
  md += `- **Icons:** ${assets.icons.length}\n`;
  md += `- **Patterns:** ${assets.patterns.length}\n`;
  md += `- **Frame Sequences:** ${assets.frames.length}\n\n`;

  // Images
  md += `## 📸 Images (${assets.images.length})\n\n`;
  md += `| Name | Path | Size | Category |\n`;
  md += `|------|------|------|----------|\n`;
  assets.images.forEach((img) => {
    md += `| ${img.name} | \`${img.path}\` | ${img.size} | ${img.category} |\n`;
  });
  md += `\n`;

  // Videos
  md += `## 🎬 Videos (${assets.videos.length})\n\n`;
  md += `| Name | Path | Size |\n`;
  md += `|------|------|------|\n`;
  assets.videos.forEach((video) => {
    md += `| ${video.name} | \`${video.path}\` | ${video.size} |\n`;
  });
  md += `\n`;

  // Models
  md += `## 🎭 3D Models (${assets.models.length})\n\n`;
  md += `| Name | Path | Size | Format |\n`;
  md += `|------|------|------|--------|\n`;
  assets.models.forEach((model) => {
    md += `| ${model.name} | \`${model.path}\` | ${model.size} | ${model.format} |\n`;
  });
  md += `\n`;

  // Icons
  md += `## 🎨 Icons (${assets.icons.length})\n\n`;
  md += `| Name | Path | Category |\n`;
  md += `|------|------|----------|\n`;
  assets.icons.forEach((icon) => {
    md += `| ${icon.name} | \`${icon.path}\` | ${icon.category} |\n`;
  });
  md += `\n`;

  // Patterns
  md += `## 🖼️ Patterns (${assets.patterns.length})\n\n`;
  md += `| Name | Path |\n`;
  md += `|------|------|\n`;
  assets.patterns.forEach((pattern) => {
    md += `| ${pattern.name} | \`${pattern.path}\` |\n`;
  });
  md += `\n`;

  // Frame Sequences
  md += `## 🎞️ Frame Sequences (${assets.frames.length})\n\n`;
  md += `| Name | Folder | Path |\n`;
  md += `|------|--------|------|\n`;
  assets.frames.forEach((frame) => {
    md += `| ${frame.name} | ${frame.folder} | \`${frame.path}\` |\n`;
  });
  md += `\n`;

  return md;
}

// Main execution
function main() {
  log('\n🔍 Scanning assets directory...', 'cyan');
  
  const assets = scanDirectory(ASSETS_DIR);
  
  log(`\n📊 Scan Results:`, 'green');
  log(`   Images: ${assets.images.length}`, 'cyan');
  log(`   Videos: ${assets.videos.length}`, 'cyan');
  log(`   Models: ${assets.models.length}`, 'cyan');
  log(`   Icons: ${assets.icons.length}`, 'cyan');
  log(`   Patterns: ${assets.patterns.length}`, 'cyan');
  log(`   Frame Sequences: ${assets.frames.length}`, 'cyan');
  
  // Generate files
  log(`\n📝 Generating files...`, 'magenta');
  
  // 1. TypeScript Registry
  const tsContent = generateTypeScriptRegistry(assets);
  const tsPath = path.join(OUTPUT_DIR, 'src', 'config', 'assets.ts');
  
  try {
    fs.mkdirSync(path.dirname(tsPath), { recursive: true });
    fs.writeFileSync(tsPath, tsContent);
    log(`   ✅ Generated: ${tsPath}`, 'green');
  } catch (error) {
    log(`   ❌ Error writing TypeScript: ${error.message}`, 'yellow');
  }
  
  // 2. Markdown Inventory
  const mdContent = generateMarkdownInventory(assets);
  const mdPath = path.join(OUTPUT_DIR, 'docs', 'ASSETS-INVENTORY.md');
  
  try {
    fs.mkdirSync(path.dirname(mdPath), { recursive: true });
    fs.writeFileSync(mdPath, mdContent);
    log(`   ✅ Generated: ${mdPath}`, 'green');
  } catch (error) {
    log(`   ❌ Error writing Markdown: ${error.message}`, 'yellow');
  }
  
  log(`\n✨ Done!\n`, 'green');
}

// Run
main();
